FROM node:20-alpine AS build-step
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build --configuration=production

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-step /app/dist/solar-flare2058/browser /usr/share/nginx/html

EXPOSE 80

